// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: storageapi/storage.proto

package storageapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Body isRequest_Body         `protobuf_oneof:"body"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_storageapi_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_storageapi_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Request) GetGetCapacity() *GetCapacityRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*request_GetCapacity); ok {
			return x.GetCapacity
		}
	}
	return nil
}

func (x *Request) GetWrite() *WriteRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*request_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *Request) GetRead() *ReadRequest {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*request_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Request) SetGetCapacity(v *GetCapacityRequest) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &request_GetCapacity{v}
}

func (x *Request) SetWrite(v *WriteRequest) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &request_Write{v}
}

func (x *Request) SetRead(v *ReadRequest) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &request_Read{v}
}

func (x *Request) HasBody() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Body != nil
}

func (x *Request) HasGetCapacity() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*request_GetCapacity)
	return ok
}

func (x *Request) HasWrite() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*request_Write)
	return ok
}

func (x *Request) HasRead() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*request_Read)
	return ok
}

func (x *Request) ClearBody() {
	x.xxx_hidden_Body = nil
}

func (x *Request) ClearGetCapacity() {
	if _, ok := x.xxx_hidden_Body.(*request_GetCapacity); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Request) ClearWrite() {
	if _, ok := x.xxx_hidden_Body.(*request_Write); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Request) ClearRead() {
	if _, ok := x.xxx_hidden_Body.(*request_Read); ok {
		x.xxx_hidden_Body = nil
	}
}

const Request_Body_not_set_case case_Request_Body = 0
const Request_GetCapacity_case case_Request_Body = 1
const Request_Write_case case_Request_Body = 2
const Request_Read_case case_Request_Body = 3

func (x *Request) WhichBody() case_Request_Body {
	if x == nil {
		return Request_Body_not_set_case
	}
	switch x.xxx_hidden_Body.(type) {
	case *request_GetCapacity:
		return Request_GetCapacity_case
	case *request_Write:
		return Request_Write_case
	case *request_Read:
		return Request_Read_case
	default:
		return Request_Body_not_set_case
	}
}

type Request_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Body:
	GetCapacity *GetCapacityRequest
	Write       *WriteRequest
	Read        *ReadRequest
	// -- end of xxx_hidden_Body
}

func (b0 Request_builder) Build() *Request {
	m0 := &Request{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GetCapacity != nil {
		x.xxx_hidden_Body = &request_GetCapacity{b.GetCapacity}
	}
	if b.Write != nil {
		x.xxx_hidden_Body = &request_Write{b.Write}
	}
	if b.Read != nil {
		x.xxx_hidden_Body = &request_Read{b.Read}
	}
	return m0
}

type case_Request_Body protoreflect.FieldNumber

func (x case_Request_Body) String() string {
	md := file_storageapi_storage_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isRequest_Body interface {
	isRequest_Body()
}

type request_GetCapacity struct {
	GetCapacity *GetCapacityRequest `protobuf:"bytes,1,opt,name=get_capacity,json=getCapacity,oneof"`
}

type request_Write struct {
	Write *WriteRequest `protobuf:"bytes,2,opt,name=write,oneof"`
}

type request_Read struct {
	Read *ReadRequest `protobuf:"bytes,3,opt,name=read,oneof"`
}

func (*request_GetCapacity) isRequest_Body() {}

func (*request_Write) isRequest_Body() {}

func (*request_Read) isRequest_Body() {}

type Response struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Body isResponse_Body        `protobuf_oneof:"body"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_storageapi_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_storageapi_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Response) GetGetCapacity() *GetCapacityResponse {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*response_GetCapacity); ok {
			return x.GetCapacity
		}
	}
	return nil
}

func (x *Response) GetWrite() *WriteResponse {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*response_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *Response) GetRead() *ReadResponse {
	if x != nil {
		if x, ok := x.xxx_hidden_Body.(*response_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Response) SetGetCapacity(v *GetCapacityResponse) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &response_GetCapacity{v}
}

func (x *Response) SetWrite(v *WriteResponse) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &response_Write{v}
}

func (x *Response) SetRead(v *ReadResponse) {
	if v == nil {
		x.xxx_hidden_Body = nil
		return
	}
	x.xxx_hidden_Body = &response_Read{v}
}

func (x *Response) HasBody() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Body != nil
}

func (x *Response) HasGetCapacity() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*response_GetCapacity)
	return ok
}

func (x *Response) HasWrite() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*response_Write)
	return ok
}

func (x *Response) HasRead() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Body.(*response_Read)
	return ok
}

func (x *Response) ClearBody() {
	x.xxx_hidden_Body = nil
}

func (x *Response) ClearGetCapacity() {
	if _, ok := x.xxx_hidden_Body.(*response_GetCapacity); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Response) ClearWrite() {
	if _, ok := x.xxx_hidden_Body.(*response_Write); ok {
		x.xxx_hidden_Body = nil
	}
}

func (x *Response) ClearRead() {
	if _, ok := x.xxx_hidden_Body.(*response_Read); ok {
		x.xxx_hidden_Body = nil
	}
}

const Response_Body_not_set_case case_Response_Body = 0
const Response_GetCapacity_case case_Response_Body = 2
const Response_Write_case case_Response_Body = 3
const Response_Read_case case_Response_Body = 4

func (x *Response) WhichBody() case_Response_Body {
	if x == nil {
		return Response_Body_not_set_case
	}
	switch x.xxx_hidden_Body.(type) {
	case *response_GetCapacity:
		return Response_GetCapacity_case
	case *response_Write:
		return Response_Write_case
	case *response_Read:
		return Response_Read_case
	default:
		return Response_Body_not_set_case
	}
}

type Response_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Body:
	GetCapacity *GetCapacityResponse
	Write       *WriteResponse
	Read        *ReadResponse
	// -- end of xxx_hidden_Body
}

func (b0 Response_builder) Build() *Response {
	m0 := &Response{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GetCapacity != nil {
		x.xxx_hidden_Body = &response_GetCapacity{b.GetCapacity}
	}
	if b.Write != nil {
		x.xxx_hidden_Body = &response_Write{b.Write}
	}
	if b.Read != nil {
		x.xxx_hidden_Body = &response_Read{b.Read}
	}
	return m0
}

type case_Response_Body protoreflect.FieldNumber

func (x case_Response_Body) String() string {
	md := file_storageapi_storage_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isResponse_Body interface {
	isResponse_Body()
}

type response_GetCapacity struct {
	GetCapacity *GetCapacityResponse `protobuf:"bytes,2,opt,name=get_capacity,json=getCapacity,oneof"`
}

type response_Write struct {
	Write *WriteResponse `protobuf:"bytes,3,opt,name=write,oneof"`
}

type response_Read struct {
	Read *ReadResponse `protobuf:"bytes,4,opt,name=read,oneof"`
}

func (*response_GetCapacity) isResponse_Body() {}

func (*response_Write) isResponse_Body() {}

func (*response_Read) isResponse_Body() {}

type GetCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityRequest) Reset() {
	*x = GetCapacityRequest{}
	mi := &file_storageapi_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityRequest) ProtoMessage() {}

func (x *GetCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storageapi_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetCapacityRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetCapacityRequest_builder) Build() *GetCapacityRequest {
	m0 := &GetCapacityRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetCapacityResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NumBlocks   uint64                 `protobuf:"varint,1,opt,name=num_blocks,json=numBlocks"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetCapacityResponse) Reset() {
	*x = GetCapacityResponse{}
	mi := &file_storageapi_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityResponse) ProtoMessage() {}

func (x *GetCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storageapi_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetCapacityResponse) GetNumBlocks() uint64 {
	if x != nil {
		return x.xxx_hidden_NumBlocks
	}
	return 0
}

func (x *GetCapacityResponse) SetNumBlocks(v uint64) {
	x.xxx_hidden_NumBlocks = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetCapacityResponse) HasNumBlocks() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetCapacityResponse) ClearNumBlocks() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_NumBlocks = 0
}

type GetCapacityResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NumBlocks *uint64
}

func (b0 GetCapacityResponse_builder) Build() *GetCapacityResponse {
	m0 := &GetCapacityResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NumBlocks != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_NumBlocks = *b.NumBlocks
	}
	return m0
}

type WriteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BlockId     uint64                 `protobuf:"varint,1,opt,name=block_id,json=blockId"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	xxx_hidden_Offset      uint64                 `protobuf:"varint,3,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_storageapi_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storageapi_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WriteRequest) GetBlockId() uint64 {
	if x != nil {
		return x.xxx_hidden_BlockId
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *WriteRequest) GetOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *WriteRequest) SetBlockId(v uint64) {
	x.xxx_hidden_BlockId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *WriteRequest) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *WriteRequest) SetOffset(v uint64) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *WriteRequest) HasBlockId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *WriteRequest) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *WriteRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *WriteRequest) ClearBlockId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BlockId = 0
}

func (x *WriteRequest) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

func (x *WriteRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Offset = 0
}

type WriteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BlockId *uint64
	Data    []byte
	Offset  *uint64
}

func (b0 WriteRequest_builder) Build() *WriteRequest {
	m0 := &WriteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BlockId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_BlockId = *b.BlockId
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Data = b.Data
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_storageapi_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storageapi_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type WriteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 WriteResponse_builder) Build() *WriteResponse {
	m0 := &WriteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ReadRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BlockId     uint64                 `protobuf:"varint,1,opt,name=block_id,json=blockId"`
	xxx_hidden_Size        uint64                 `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_Offset      uint64                 `protobuf:"varint,3,opt,name=offset"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_storageapi_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storageapi_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadRequest) GetBlockId() uint64 {
	if x != nil {
		return x.xxx_hidden_BlockId
	}
	return 0
}

func (x *ReadRequest) GetSize() uint64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *ReadRequest) GetOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ReadRequest) SetBlockId(v uint64) {
	x.xxx_hidden_BlockId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ReadRequest) SetSize(v uint64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ReadRequest) SetOffset(v uint64) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ReadRequest) HasBlockId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReadRequest) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ReadRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ReadRequest) ClearBlockId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BlockId = 0
}

func (x *ReadRequest) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Size = 0
}

func (x *ReadRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Offset = 0
}

type ReadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BlockId *uint64
	Size    *uint64
	Offset  *uint64
}

func (b0 ReadRequest_builder) Build() *ReadRequest {
	m0 := &ReadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BlockId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_BlockId = *b.BlockId
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Size = *b.Size
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	return m0
}

type ReadResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_storageapi_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storageapi_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *ReadResponse) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ReadResponse) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ReadResponse) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

type ReadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []byte
}

func (b0 ReadResponse_builder) Build() *ReadResponse {
	m0 := &ReadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

var File_storageapi_storage_proto protoreflect.FileDescriptor

var file_storageapi_storage_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x30, 0x63, 0x6f, 0x6d, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x6d, 0x69, 0x67, 0x68, 0x74,
	0x79, 0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x66, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x69, 0x22, 0xa9, 0x02, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x69, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x5f,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x44,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6f, 0x76, 0x65, 0x72,
	0x6d, 0x69, 0x67, 0x68, 0x74, 0x79, 0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x2e, 0x67, 0x6c, 0x61, 0x6e,
	0x66, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x63,
	0x69, 0x74, 0x79, 0x12, 0x56, 0x0a, 0x05, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x6f, 0x76, 0x65, 0x72, 0x6d, 0x69, 0x67, 0x68, 0x74, 0x79, 0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x2e,
	0x67, 0x6c, 0x61, 0x6e, 0x66, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x77, 0x72, 0x69, 0x74, 0x65, 0x12, 0x53, 0x0a, 0x04, 0x72,
	0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x6d, 0x69, 0x67, 0x68, 0x74,
	0x79, 0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x66, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x61, 0x64,
	0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xad, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x61, 0x70,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x6d, 0x69, 0x67,
	0x68, 0x74, 0x79, 0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x66, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x57, 0x0a, 0x05, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x3f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6f, 0x76,
	0x65, 0x72, 0x6d, 0x69, 0x67, 0x68, 0x74, 0x79, 0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x2e, 0x67, 0x6c,
	0x61, 0x6e, 0x66, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x61, 0x70, 0x69, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x05, 0x77, 0x72, 0x69, 0x74, 0x65, 0x12, 0x54, 0x0a, 0x04, 0x72, 0x65,
	0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6f, 0x76, 0x65, 0x72, 0x6d, 0x69, 0x67, 0x68, 0x74, 0x79,
	0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x2e, 0x67, 0x6c, 0x61, 0x6e, 0x66, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x61, 0x64,
	0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x5f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x22, 0x55, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x54, 0x0a, 0x0b,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x11, 0x5a, 0x0f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x69, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_storageapi_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_storageapi_storage_proto_goTypes = []any{
	(*Request)(nil),             // 0: com.github.overmighty.glan.glanfs.api.storageapi.Request
	(*Response)(nil),            // 1: com.github.overmighty.glan.glanfs.api.storageapi.Response
	(*GetCapacityRequest)(nil),  // 2: com.github.overmighty.glan.glanfs.api.storageapi.GetCapacityRequest
	(*GetCapacityResponse)(nil), // 3: com.github.overmighty.glan.glanfs.api.storageapi.GetCapacityResponse
	(*WriteRequest)(nil),        // 4: com.github.overmighty.glan.glanfs.api.storageapi.WriteRequest
	(*WriteResponse)(nil),       // 5: com.github.overmighty.glan.glanfs.api.storageapi.WriteResponse
	(*ReadRequest)(nil),         // 6: com.github.overmighty.glan.glanfs.api.storageapi.ReadRequest
	(*ReadResponse)(nil),        // 7: com.github.overmighty.glan.glanfs.api.storageapi.ReadResponse
}
var file_storageapi_storage_proto_depIdxs = []int32{
	2, // 0: com.github.overmighty.glan.glanfs.api.storageapi.Request.get_capacity:type_name -> com.github.overmighty.glan.glanfs.api.storageapi.GetCapacityRequest
	4, // 1: com.github.overmighty.glan.glanfs.api.storageapi.Request.write:type_name -> com.github.overmighty.glan.glanfs.api.storageapi.WriteRequest
	6, // 2: com.github.overmighty.glan.glanfs.api.storageapi.Request.read:type_name -> com.github.overmighty.glan.glanfs.api.storageapi.ReadRequest
	3, // 3: com.github.overmighty.glan.glanfs.api.storageapi.Response.get_capacity:type_name -> com.github.overmighty.glan.glanfs.api.storageapi.GetCapacityResponse
	5, // 4: com.github.overmighty.glan.glanfs.api.storageapi.Response.write:type_name -> com.github.overmighty.glan.glanfs.api.storageapi.WriteResponse
	7, // 5: com.github.overmighty.glan.glanfs.api.storageapi.Response.read:type_name -> com.github.overmighty.glan.glanfs.api.storageapi.ReadResponse
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_storageapi_storage_proto_init() }
func file_storageapi_storage_proto_init() {
	if File_storageapi_storage_proto != nil {
		return
	}
	file_storageapi_storage_proto_msgTypes[0].OneofWrappers = []any{
		(*request_GetCapacity)(nil),
		(*request_Write)(nil),
		(*request_Read)(nil),
	}
	file_storageapi_storage_proto_msgTypes[1].OneofWrappers = []any{
		(*response_GetCapacity)(nil),
		(*response_Write)(nil),
		(*response_Read)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storageapi_storage_proto_rawDesc), len(file_storageapi_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storageapi_storage_proto_goTypes,
		DependencyIndexes: file_storageapi_storage_proto_depIdxs,
		MessageInfos:      file_storageapi_storage_proto_msgTypes,
	}.Build()
	File_storageapi_storage_proto = out.File
	file_storageapi_storage_proto_goTypes = nil
	file_storageapi_storage_proto_depIdxs = nil
}
